### ISSUE TITLE
Android Systrace tool throwing errors

### ISSUE THREAD

**Issue by Manikkumar1988** [googlecodelabs/android-perf-testing#44]
`python C:\Users\username\AppData\Local\Android\Sdk\platform-tools\systrace\systrace.py --time=5 -o mynewtrace.html gfx`

Starting tracing (5 seconds)
Tracing completed. Collecting output...
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Android\Sdk\platform-tools\systrace\systrace.py", line 49, in <module>
    sys.exit(run_systrace.main())
  File "C:\Users\username\AppData\Local\Android\Sdk\platform-tools\systrace\catapult\systrace\systrace\run_systrace.py", line 196, in main
    main_impl(sys.argv)
  File "C:\Users\username\AppData\Local\Android\Sdk\platform-tools\systrace\catapult\systrace\systrace\run_systrace.py", line 191, in main_impl
    controller.StopTracing()
  File "C:\Users\username\AppData\Local\Android\Sdk\platform-tools\systrace\catapult\systrace\systrace\systrace_runner.py", line 48, in StopTracing
    self._tracing_controller.StopTracing()
  File "C:\Users\username\AppData\Local\Android\Sdk\platform-tools\systrace\catapult\systrace\systrace\tracing_controller.py", line 183, in StopTracing
    self._IssueClockSyncMarker()
  File "C:\Users\username\AppData\Local\Android\Sdk\platform-tools\systrace\catapult\systrace\systrace\tracing_controller.py", line 239, in _IssueClockSyncMarker
    agent.RecordClockSyncMarker(sync_id, ControllerAgentClockSync)
  File "C:\Users\username\AppData\Local\Android\Sdk\platform-tools\systrace\catapult\systrace\systrace\tracing_agents\atrace_agent.py", line 229, in RecordClockSyncMarker
    shell.RunCommand(cmd, close=True)
  File "C:\Users\username\AppData\Local\Android\Sdk\platform-tools\systrace\catapult\systrace\systrace\..\..\devil\devil\android\sdk\adb_wrapper.py", line 213, in RunCommand
    return (result[:-1], int(result[-1]))
ValueError: invalid literal for int() with base 10: ''

C:\Users\username>python systrace.py --time=5 -o mynewtrace.html gfx
python: can't open file 'systrace.py': [Errno 2] No such file or directory

**Comment by Manikkumar1988** [comment]
Another user faces same issue
https://stackoverflow.com/q/50249481/2700586

**Comment by Manikkumar1988** [comment]
Any Update on this?

**Comment by Manikkumar1988** [comment]
Unable to use the systrace feature itself!

**Comment by chronvas** [comment]
The systrace works on Mac with python version `Python 2.7.10`. Which version are you using?

**Comment by arkantos1482** [comment]
I have the same issue,
it seems it somehow related to phone we are testing.
Since it worked on Emulator (which allows to log only disk traces). But I tried with various actual phones and faced the same failure @Manikkumar1988  reported.

**Comment by gongshoudao** [comment]
I have same issue too

**Comment by robling** [comment]
Try upgrade you SDK platform-tool version, useful for me
